const products=[
{id:1,name:'Form No. 01 Table Lamp',category:'Lighting',price:148,tag:'Bestseller',img:'photo-1507473885765-e6ed057f782c'},
{id:2,name:'Arc Sculptural Vase',category:'Decor',price:86,tag:'New',img:'photo-1578500494198-246f612d3b3d'},
{id:3,name:'Sunday Throw',category:'Textiles',price:124,tag:'',img:'photo-1600210492486-724fe5c67fb0'},
{id:4,name:'Pebble Catchall',category:'Decor',price:42,tag:'',img:'photo-1610701596007-11502861dcfa'},
{id:5,name:'Sol Pendant Light',category:'Lighting',price:220,tag:'Small batch',img:'photo-1507473885765-e6ed057f782c'},
{id:6,name:'Linen Cushion Cover',category:'Textiles',price:68,tag:'',img:'photo-1584100936595-c0654b55a2e2'},
{id:7,name:'Forma Ceramic Bowl',category:'Decor',price:54,tag:'',img:'photo-1490312278390-ab64016e0aa9'},
{id:8,name:'Dusk Bedside Light',category:'Lighting',price:176,tag:'Bestseller',img:'photo-1507473885765-e6ed057f782c'}];
const photo=id=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=700&q=80`;let cart=JSON.parse(localStorage.getItem('formaCart')||'{}'),category='All';
function save(){localStorage.setItem('formaCart',JSON.stringify(cart));document.getElementById('count').textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
function renderProducts(){let items=category==='All'?products:products.filter(p=>p.category===category);document.getElementById('result-count').textContent=`${items.length} pieces`;document.getElementById('products').innerHTML=items.map(p=>`<article class="card"><div class="product-img"><img src="${photo(p.img)}" alt="${p.name}" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button class="quick" onclick="add(${p.id})">ADD TO BAG&nbsp; +</button></div><div class="product-meta"><span class="product-name">${p.name}</span><span class="price">$${p.price}</span></div><div class="category">${p.category}</div></article>`).join('')}
function setCategory(c,btn){category=c;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.textContent.toLowerCase().startsWith(c.toLowerCase())||(c==='All'&&x.textContent==='All objects')));renderProducts()}
function add(id){cart[id]=(cart[id]||0)+1;save();toast('Added to your bag');renderCart()}
function change(id,n){cart[id]=(cart[id]||0)+n;if(cart[id]<=0)delete cart[id];save();renderCart()}
function removeItem(id){delete cart[id];save();renderCart()}
function renderCart(){let rows=Object.entries(cart),el=document.getElementById('cart-items'),bottom=document.getElementById('cart-bottom');document.getElementById('bag-number').textContent=rows.length?`(${rows.reduce((n,[,q])=>n+q,0)})`:'';if(!rows.length){el.innerHTML='<div class="empty"><b>Your bag is taking a quiet moment.</b>Find something lovely for your space.<br><br><button class="primary" onclick="closePanels();document.querySelector(\'#shop\').scrollIntoView({behavior:\'smooth\'})">EXPLORE OBJECTS</button></div>';bottom.innerHTML='';return}let total=0;el.innerHTML=rows.map(([id,q])=>{let p=products.find(x=>x.id==id);total+=p.price*q;return `<div class="cart-row"><img src="${photo(p.img)}" alt="${p.name}"><div><h3>${p.name}</h3><p>$${p.price}</p><div class="qty"><button onclick="change(${id},-1)">âˆ’</button>${q}<button onclick="change(${id},1)">+</button></div><button class="remove" onclick="removeItem(${id})">Remove</button></div><b>$${p.price*q}</b></div>`}).join('');bottom.innerHTML=`<div class="total"><span>Subtotal</span><strong>$${total.toFixed(2)}</strong></div><p class="note">Shipping calculated at checkout.</p><button class="primary checkout" onclick="toast('Checkout is a preview for now')">CONTINUE TO CHECKOUT&nbsp; â†—</button>`}
function openCart(){renderCart();document.getElementById('overlay').classList.add('show');document.getElementById('drawer').classList.add('open')}
function closePanels(){document.getElementById('overlay').classList.remove('show');document.getElementById('drawer').classList.remove('open');document.getElementById('modal').classList.remove('show')}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)}
function openModal(view){let modal=document.getElementById('modal'),box=document.getElementById('modal-content');modal.classList.add('show');if(view==='auth'){box.innerHTML=`<button class="close" style="position:absolute;right:20px;top:17px" onclick="closePanels()">Ã—</button><div class="eyebrow">Welcome to Forma</div><h2 id="auth-title">Come on in.</h2><p id="auth-copy">Sign in to save your favourites and keep track of your orders.</p><button class="google" onclick="toast('Google sign-in is a preview for now')">G&nbsp;&nbsp; Continue with Google</button><div class="divider">OR WITH EMAIL</div><label>Email address</label><input type="email" id="email" placeholder="you@example.com"><div id="password-field"><label>Password</label><input type="password" placeholder="At least 8 characters"></div><button class="primary" onclick="toast('Account sign-in is a preview for now')">SIGN IN</button><div class="switch">New to Forma? <button class="textbutton" onclick="authSignup()">Create an account</button></div>`}else{let orders=JSON.parse(localStorage.getItem('formaOrders')||'[]');box.innerHTML=`<button class="close" style="position:absolute;right:20px;top:17px" onclick="closePanels()">Ã—</button><div class="eyebrow">Your account</div><h2>Your orders.</h2><p>Sign in to view your order history.</p>${orders.length?orders.map(o=>`<div class="account-order"><strong>${o.id}</strong><span>${o.date} Â· ${o.status} Â· $${o.total}</span></div>`).join(''):'<div class="empty"><b>No orders just yet.</b>Your next favourite is waiting.</div>'}<button class="primary" style="width:100%" onclick="openModal('auth')">SIGN IN</button>`}}
function authSignup(){document.getElementById('auth-title').textContent='A lovely place to start.';document.getElementById('auth-copy').textContent='Create an account to save favourites and follow your orders.';document.querySelector('.modal-card .primary').textContent='CREATE ACCOUNT';document.querySelector('.switch').innerHTML='Already have an account? <button class="textbutton" onclick="openModal(\'auth\')">Sign in</button>'}
function openOrders(){openModal('orders')}document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels()});save();renderProducts();
